Vagrant.configure("2") do |config|
  config.vm.define "Ubuntu 18.04 LTS - Nginx" do |machine|
    machine.vm.box = "hashicorp/bionic64"
    machine.vm.network "forwarded_port", guest: 80, host: 8080
    machine.vm.synced_folder "api/", "/var/www/html"
    machine.vm.provision "shell", path: "provision/script.sh"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end

